name: "Release Binary"

on:
  push:
    branches:
      - main

jobs:
  build-tar-ball:
    name: "Build and Tar Ball"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: "openbmclapi-linux.tar.xz"
          - os: windows-latest
            artifact_name: "openbmclapi-windows.tar.gz"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Prepare Artifact
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cp $(which node) .
            cp platforms/linux/run.sh .
            tar -caf ${{ matrix.artifact_name }} dist package.json node_modules run.sh
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            $SRC = (Get-Command node.exe).Path
            copy $SRC node.exe
            copy platforms/windows/run.ps1 .
            tar -caf ${{ matrix.artifact_name }} dist package.json node_modules node.exe run.ps1
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
